# Generated by Django A.B on YYYY-MM-DD HH:MM
from django.db import migrations, connection
from wagtail.documents.models import Document as WTDocument
from wagtail.documents.models import get_document_model

def import_documents(apps, schema_editor):
    documents = get_document_model().objects.all()
    with connection.cursor() as cursor:
        for wtdoc in WTDocument.objects.exclude(id__in=documents):
            cursor.execute('Insert into wagtail_textract_document (document_ptr_id, transcription) values (%s, \'\')', [wtdoc.id])


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_textract', '0002_auto_20180509_1259'),
    ]

    operations = [
        migrations.RunPython(import_documents)
    ]